# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Max Sumrall
email: jmsumrall@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Max Sumrall. This is my personal site to learn about me. Thanks for reading!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.maxsumrall.com" # the base hostname & protocol for your site
twitter_username: MaxSumrall
github_username:  maxsumrall

# Build settings
markdown: kramdown

gems:
  - jekyll-seo-tag